# This file generates the GitHub Actions matrix.
# The generate_build_yaml.py output will overwrite this list at runtime

board:
  - nice_nano_v2

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - settings_reset

format:
  - bt
  - dongle
  - reset

keymap:
  - qwerty
  - colemak_dh
  - graphite

# only use `include:` for the one-off snippet overrides
include:
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: colemak_dh
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: graphite
    snippet: studio-rpc-usb-uart
