services:
  builder:
    image: zmkfirmware/zmk-dev-arm:stable
    volumes:
      # Bind-mount entire repo read-only
      - ../:/workspaces/zmk:ro
      # Persist built firmware to host
      - ../firmwares:/workspaces/zmk-firmwares:rw
    working_dir: /workspaces/zmk
    entrypoint: []
    command:
      - bash
      - ./local-build/build_setup.sh
    tty: true
    stdin_open: true