draw_config:
  # key sizing
  key_w: 60
  key_h: 60
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  draw_key_sides: false
  # add breathing room around each keycap
  inner_pad_w: 4.0
  inner_pad_h: 4.0
  # outer_pad_h: 20   # adds top/bottom padding
  outer_pad_w: 125   # optional left/right padding
  legend_rel_x: 2.0
  legend_rel_y: 2.0


  # styling hooks
  svg_extra_style: |
    /* ── Hide Layer Names ───────────────────────────────────── */
    text.label { display: none; }

    /* ── Keycap Text Color ───────────────────────────────────── */
    text.tap { font-family: "JetBrainsMono Nerd Font"; fill: #00e2cd; font-size: 16px; }

    /* ── Keycap Background Color ───────────────────────────────────── */
    rect.key { fill: #363B3D; }

    /* ── Combo Highlight Color ───────────────────────────────────── */
    rect.combo, rect.combo-separate { fill: #3f403c; }

parse_config:
  preprocess: true
  skip_binding_parsing: false
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  raw_binding_map:
    "&caps_word": "CAPS WORD"
    "&td_bore": "L_BASE L_EXTRA"
    "&mkp LCLK": "Left Click"
    "&mkp MCLK": "Mid Click"
    "&mkp RCLK": "Right Click"
