name: Draw BASE keymaps

on:
  push:
    branches:
      - '*' 

jobs:
  draw_base_keymap:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/keymap/qwerty.keymap"
      config_path:    "keymap-drawer/config.yaml"
      output_folder:  "keymap-drawer/base"
      json_path:      "config"
      parse_args:     "-c 12"
      draw_args:      "qwerty:'-s BASE --keys-only'"
      amend_commit:   false
      commit_message: "Add BASE-layer keymaps"
      destination:    commit
      fail_on_error:  true
      debug_mode:     false
