name: Draw keymaps
run-name: Draw keymaps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draw_keymaps:
    name: Generate Keymaps
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install keymap-drawer
        run: |
          # Ubuntu has made it difficult to install keymap-drawer globally, so using venv instead
          python3 -m venv venv
          ./venv/bin/pip install keymap-drawer pyyaml
          echo "$(pwd)/venv/bin" >> $GITHUB_PATH

      - name: Parse keymap
        run: |
          keymap -c keymap-drawer/config.yaml parse -c 12 -z config/keymaps/qwerty.keymap \
            > keymap-drawer/stacked/qwerty.yaml

      - name: Generate stacked YAML
        run: python3 scripts/make_stacked.py

      - name: Draw stacked keymap
        run: |
          keymap -c keymap-drawer/config.yaml draw -j config/qwerty.json \
            keymap-drawer/stacked/stacked.yaml > keymap-drawer/stacked/stacked.svg

      - name: Draw all-layers keymap
        run: |
          mkdir -p keymap-drawer/all-layers
          keymap -c keymap-drawer/config.yaml draw -j config/qwerty.json \
            keymap-drawer/stacked/qwerty.yaml > keymap-drawer/all_layers/all_layers.svg

      - name: Set permissions
        run: |
          chmod 777 keymap-drawer/stacked/stacked.svg
          chmod 777 keymap-drawer/all_layers/all_layers.svg

      - name: Auto-commit keymap drawings
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update keymap drawings"
          file_pattern: keymap-drawer
          # skip_push: true
