name: Draw FULL keymaps
run-name: Draw FULL keymaps

on:
  workflow_run:
    workflows:
      - Draw BASE keymaps
    types:
      - completed

jobs:
  draw_full_keymap:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/keymap/qwerty.keymap"
      config_path:    "keymap-drawer/config.yaml"
      output_folder:  "keymap-drawer"
      json_path:      ""
      parse_args:     "-c 12"
      draw_args:      "qwerty:'--zmk-keyboard qwerty'"
      amend_commit:   false
      commit_message: "Add full keymaps"
      destination:    both
      fail_on_error:  true
      debug_mode:     false
