name: Run single ZMK build

on:
  workflow_call:
    inputs:
      board:
        required: true
        type: string
      shield:
        required: true
        type: string
      keymap:
        required: true
        type: string
      format:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create single-entry build.yaml
        run: |
          echo "include:" > build.yaml
          echo "  - board: ${{ inputs.board }}" >> build.yaml
          echo "    shield: ${{ inputs.shield }}" >> build.yaml
          echo "    keymap: ${{ inputs.keymap }}" >> build.yaml
          echo "    format: ${{ inputs.format }}" >> build.yaml

      - name: Run ZMK upstream build
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          build_matrix_path: build.yaml
          config_path: config

      - name: Rename firmware artifact
        run: |
          mkdir -p renamed
          ZIP=$(ls artifact/*.zip | head -n 1)
          NAME="${{ inputs.board }}_${{ inputs.shield }}_${{ inputs.keymap }}_${{ inputs.format }}.zip"
          mv "$ZIP" "renamed/$NAME"

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.board }}_${{ inputs.shield }}_${{ inputs.keymap }}_${{ inputs.format }}
          path: renamed/
